import Foundation

/// Japanese copy for every `fanBarText` / `fanBarFormat` call, keyed by the
/// call's English string so the call sites keep their two-literal form.
/// Terms follow macOS's own Japanese (システム設定, ログイン項目と機能拡張).
/// `JapaneseCatalogTests` fails if a call site has no entry here or if an
/// entry's format specifiers drift from its English template.
enum JapaneseCatalog {
    static func text(for english: String) -> String? {
        strings[english]
    }

    static let strings: [String: String] = [
        "%.0f°C · %.0f%%": "%.0f°C · %.0f%%",
        "%.0f°C, %.0f%%": "%.0f°C、%.0f%%",
        "%@ %.0f°C": "%@ %.0f°C",
        "%@ curve": "%@のカーブ",
        "%@ reached the high-temperature threshold of %.0f°C. Check the current workload and cooling.": "%@ が高温しきい値 %.0f°C に達しました。現在の負荷と冷却状態を確認してください。",
        "%@ RPM": "%@ RPM",
        "%@ · %.0f°C → %@": "%@ · %.0f°C → %@",
        "%@: %.0f°C · %.0f%%": "%@：%.0f°C · %.0f%%",
        "%@–%@ RPM": "%@–%@ RPM",
        "%d control points": "制御点 %d 個",
        "%d h %d m %d s remaining": "残り %d 時間 %d 分 %d 秒",
        "%d m %d s remaining": "残り %d 分 %d 秒",
        "%d of %d": "%d 番目 / 全 %d 件",
        "%d RPM": "%d RPM",
        "%d%%": "%d%%",
        "%d°C": "%d°C",
        ", ": "、",
        "1 hour": "1 時間",
        "15 minutes": "15 分",
        "30 minutes": "30 分",
        "Add a control point after this one": "この制御点の後に制御点を追加",
        "Adjust cooling": "必要に応じて冷却を調整",
        "Adjusting cooling needs one-time permission": "冷却の調整には 1 回だけ許可が必要です",
        "Advanced": "詳細",
        "Alert temperature": "通知する温度",
        "Allow FanBar in Login Items & Extensions": "「ログイン項目と機能拡張」で FanBar を許可してください",
        "Aluminum": "アルミニウム",
        "Animation": "アニメーション",
        "Animations redraw continuously. Turning them off lowers FanBar's CPU use; panel animation runs only while the panel is open.": "アニメーションは画面を継続的に再描画します。オフにすると FanBar の CPU 使用率が下がります。パネルのアニメーションはパネルを開いている間だけ動作します。",
        "App Icon": "App アイコン",
        "Appearance": "外観",
        "Appears in the menu bar after you sign in.": "ログイン後、メニューバーに表示されます。",
        "Apply": "適用",
        "Approve control service": "制御サービスを承認",
        "Approve the control service in Login Items & Extensions": "「ログイン項目と機能拡張」で制御サービスを承認",
        "Approve the updated control service in System Settings": "システム設定で更新された制御サービスを承認してください",
        "Automatic": "自動",
        "automatic": "自動",
        "Automatic restore": "自動復帰",
        "Automatically check for updates": "アップデートを自動的に確認",
        "Balanced": "バランス",
        "Battery": "バッテリー",
        "Bold": "ボールド",
        "Buffer %d°C · Step %d%%": "バッファ %d°C · ステップ %d%%",
        "Cancel": "キャンセル",
        "Ceramic": "セラミック",
        "Ceramic Lined": "セラミック・ライン",
        "Check for Updates…": "アップデートを確認…",
        "Check live status": "リアルタイムの状態を確認",
        "Choose a fixed RPM": "固定回転数を選択",
        "Choose an app icon": "App アイコンを選択",
        "Choose FanBar's icon and what it shows in the menu bar.": "メニューバーに表示する FanBar のアイコンと内容を選択します。",
        "Classic": "クラシック",
        "Collapsed": "折りたたみ",
        "Control failed: %@": "制御に失敗しました：%@",
        "Control mode": "制御モード",
        "Control mode switch failed": "制御モードを切り替えられませんでした",
        "Control point %d": "制御点 %d",
        "Control service": "制御サービス",
        "Control service enabled": "制御サービスが有効になりました",
        "Control service is missing from the app bundle": "App バンドルに制御サービスが含まれていません",
        "Control service is not enabled": "制御サービスが有効になっていません",
        "Control service is off": "制御サービスはオフです",
        "Control service unavailable": "制御サービスを利用できません",
        "Control service update failed; reopen FanBar": "制御サービスを更新できませんでした。FanBar を開き直してください",
        "Cooling": "冷却",
        "Cooling buffer": "冷却バッファ",
        "cooling fraction": "冷却率",
        "Cooling fraction must be between 0% and 100%": "冷却率は 0% から 100% の範囲で指定してください",
        "CPU only": "CPU のみ",
        "CPU temperature": "CPU 温度",
        "Current version %@": "現在のバージョン %@",
        "Custom RPM": "カスタム回転数",
        "Custom RPM…": "カスタム回転数…",
        "Dark": "ダーク",
        "Decrease fan speed": "回転数を下げる",
        "Decrease temperature": "温度を下げる",
        "Default %.0f°C.": "デフォルトは %.0f°C です。",
        "Dismiss error": "エラーを閉じる",
        "Drag a control point, or select one and fine-tune its Temp and Speed. 0% returns the fans to idle.": "制御点をドラッグするか、選択して「温度」「回転数」で微調整します。0% はファンをアイドルに戻します。",
        "Drag control points to set temperature and speed; use the steppers below for the selected point": "制御点をドラッグして温度と回転数を設定します。選択した点は下のステッパーで微調整できます",
        "Draggable cooling curve": "ドラッグで編集できる冷却カーブ",
        "Enable": "有効にする",
        "Enable and approve the control service first": "先に制御サービスを有効にして承認してください",
        "Enable it for cooling presets and manual control": "有効にすると冷却プリセットと手動制御を使用できます",
        "Enabled": "有効",
        "Enter %@–%@ RPM": "%@–%@ RPM の範囲で入力",
        "Enter a whole number": "整数を入力してください",
        "Expand to edit the cooling buffer and maximum step": "展開して冷却バッファと 1 回あたりの最大変化量を編集",
        "Expanded": "展開",
        "Extreme": "最大",
        "Fan %d": "ファン %d",
        "Fan %d was not found": "ファン %d が見つかりません",
        "Fan Control": "ファン制御",
        "Fan control failed": "ファン制御に失敗しました",
        "Fan speed": "ファン回転数",
        "FanBar High Temperature Warning": "FanBar 高温警告",
        "FanBar is free and open source · Star it on GitHub": "FanBar は無料のオープンソースです · GitHub でスターをお願いします",
        "FanBar is running": "FanBar は起動しています",
        "FanBar Settings": "FanBar 設定",
        "FanBar, %@": "FanBar、%@",
        "FanBar, %@ mode": "FanBar、%@モード",
        "Find it here": "ここにあります",
        "Fixed": "固定",
        "Fixed RPM": "固定回転数",
        "Fixed target: %d RPM": "固定目標：%d RPM",
        "General": "一般",
        "GPU only": "GPU のみ",
        "Guard": "ガード",
        "Heat alert": "高温通知",
        "High-temperature alerts": "高温通知",
        "Higher of CPU/GPU": "CPU/GPU の高い方",
        "Holds higher RPM while cooling to reduce chatter.": "温度が下がる間は高めの回転数を保ち、回転数の上下を減らします。",
        "Icon": "アイコン",
        "Icon only": "アイコンのみ",
        "Idle (target 0 RPM)": "アイドル（0 RPM）",
        "Increase fan speed": "回転数を上げる",
        "Increase temperature": "温度を上げる",
        "Interface language": "表示言語",
        "It lives in the menu bar at the top of your screen and does not appear in the Dock.": "画面上部のメニューバーに常駐し、Dock には表示されません。",
        "Keep automatic control for everyday use": "普段は自動制御のままで問題ありません",
        "Keep the menu bar minimal with only the current mode icon.": "現在のモードのアイコンだけを表示し、メニューバーをすっきり保ちます。",
        "Launch FanBar at login": "ログイン時に FanBar を起動",
        "Limits how far speed can change in one update.": "1 回の更新で変化できる回転数の幅を制限します。",
        "macOS automatic control restored": "macOS の自動制御に戻りました",
        "Managed automatically by macOS": "macOS が自動で管理",
        "manual": "手動",
        "Manual modes hand back to macOS when time runs out. Menu changes apply to that session only.": "手動モードは時間になると macOS に制御を戻します。メニューでの変更はその回にのみ適用されます。",
        "Materials": "質感",
        "Max step per update": "1 回あたりの最大変化量",
        "Menu Bar": "メニューバー",
        "Menu bar icon": "メニューバーアイコン",
        "Menu bar icon animation": "メニューバーアイコンのアニメーション",
        "Never": "自動で戻さない",
        "No temperature is available for %@ curve control": "%@のカーブ制御に使える温度を取得できません",
        "Not now": "後で",
        "Notification permission was not granted. Allow FanBar notifications in System Settings.": "通知が許可されていません。システム設定で FanBar の通知を許可してください。",
        "Notifications": "通知",
        "Now %.0f°C → %@": "現在 %.0f°C → %@",
        "Off": "オフ",
        "One alert per high-temperature episode; it resets after cooling down.": "高温状態 1 回につき通知は 1 回です。温度が下がった後に再び上がると、もう一度通知します。",
        "Only requests signed by the same developer are accepted": "同じデベロッパの署名があるリクエストのみ受け付けます",
        "Open FanBar Settings": "FanBar の設定を開く",
        "Open menu bar panel": "メニューバーパネルを開く",
        "Open System Settings": "システム設定を開く",
        "Open the FanBar GitHub repository in a browser": "ブラウザで FanBar の GitHub リポジトリを開く",
        "Outline": "アウトライン",
        "Outside the hardware range": "ハードウェアの範囲外です",
        "Panel animation": "パネルのアニメーション",
        "Performance": "高性能",
        "Pixel": "ピクセル",
        "Point %d of %d": "制御点 %d / %d",
        "Presets": "プリセット",
        "Propeller": "プロペラ",
        "Quick start": "クイックスタート",
        "Quit FanBar": "FanBar を終了",
        "Reading fans…": "ファンを読み取り中…",
        "Reading temperature": "温度を読み取り中",
        "Reinstall the signed FanBar app": "署名済みの FanBar を再インストールしてください",
        "Remove this control point": "この制御点を削除",
        "Replay quick start": "クイックスタートをもう一度見る",
        "Reset Default Curve": "デフォルトのカーブに戻す",
        "Reset to Default": "デフォルトに戻す",
        "Restore automatic control": "自動制御に戻す",
        "Restore failed: %@": "復帰に失敗しました：%@",
        "Restore this preset's default curve; use Undo to recover edits": "このプリセットのデフォルトのカーブに戻します。「取り消す」で編集内容を元に戻せます",
        "Restores after %@": "%@後に自動制御に戻ります",
        "Restoring system control…": "システム制御に戻しています…",
        "Ringed": "リング",
        "RPM must be a finite, non-negative number": "回転数は 0 以上の有限の数値で指定してください",
        "Running": "動作中",
        "Safe range %d–%d RPM": "安全範囲 %d–%d RPM",
        "Select a preset to edit its curve. Check “Show in menu” to add it as a shortcut button in the menu panel, up to two.": "プリセットを選ぶとカーブを編集できます。「メニューに表示」をオンにすると、メニューパネルにショートカットボタンとして表示されます（最大 2 つ）。",
        "Selected, %d of %d": "選択中、%d 番目 / 全 %d 件",
        "Settings": "設定",
        "Settings…": "設定…",
        "Show %@ in the menu panel": "メニューパネルに「%@」を表示",
        "Show a shortcut button for %@ in the menu panel": "メニューパネルに「%@」のショートカットボタンを表示",
        "Show CPU temperature and average fan speed together.": "CPU 温度とファンの平均回転数を並べて表示します。",
        "Show in menu": "メニューに表示",
        "Show the average RPM across all fans with grouping separators.": "すべてのファンの平均回転数を桁区切りで表示します。",
        "Show the current CPU temperature for a quick load check.": "現在の CPU 温度を表示し、負荷をすばやく確認できます。",
        "Shown in menu %d / %d": "メニューに表示 %d / %d",
        "Silent": "静音",
        "Smart cooling update failed: %@": "スマート冷却を更新できませんでした：%@",
        "SMC key %@ returned invalid data": "SMC キー %@ が無効なデータを返しました",
        "SMC operation %@ failed (%d)": "SMC 操作 %@ に失敗しました（%d）",
        "Speed": "回転数",
        "Spinning fans and mode transitions in the menu bar panel. RPM readings still update live.": "メニューバーパネルのファンの回転とモード切り替えの演出です。オフにしても回転数はリアルタイムで更新されます。",
        "SSD": "SSD",
        "Stack temperature above fan speed to take less menu bar width.": "温度を上、回転数を下に重ねて表示し、メニューバーの幅を節約します。",
        "Styles": "スタイル",
        "Swirl": "渦巻き",
        "Switch to the %@ panel preset": "パネルプリセット「%@」に切り替え",
        "Switching control mode": "制御モードを切り替え中",
        "Switching to %@ curve…": "%@のカーブに切り替え中…",
        "Switching to %d RPM…": "%d RPM に切り替え中…",
        "Target %@ (curve output %.0f%%)": "目標 %@（カーブ出力 %.0f%%）",
        "Temp": "温度",
        "Temperature + fan speed": "温度と回転数",
        "Temperature over fan speed": "温度と回転数（2 段）",
        "Temperature sensor unavailable; restoring system control…": "温度センサーを利用できません。システム制御に戻しています…",
        "Temperature source": "温度ソース",
        "Temperature trends": "温度の推移",
        "Temperature trends over the last ten minutes": "過去 10 分間の温度の推移",
        "Temperature, fan speed, and current mode": "温度、ファン回転数、現在のモード",
        "That RPM is outside the fans' supported range": "その回転数はファンの対応範囲外です",
        "The fan control service did not respond. Reauthorize it or restart FanBar.": "ファン制御サービスが応答しません。再度承認するか、FanBar を再起動してください。",
        "The FanBar fan icon in the menu bar at the top of the screen": "画面上部のメニューバーにある FanBar のファンアイコン",
        "The hub turns solid while FanBar controls the fans.": "FanBar がファンを制御している間、アイコンの中心が塗りつぶされます。",
        "The icon spins with the fans and coasts to a stop when they halt.": "ファンの回転に合わせてアイコンが回り、ファンが止まるとゆっくり停止します。",
        "The menu panel shows up to two presets. Uncheck one to choose another.": "メニューパネルに表示できるプリセットは 2 つまでです。別のものを選ぶには、どれか 1 つのチェックを外してください。",
        "This Mac did not return readable fan data.": "この Mac から読み取れるファンのデータが返されませんでした。",
        "This Mac does not support SMC key %@ (error %d).": "この Mac は SMC キー %@ に対応していません（エラー %d）。",
        "This Mac's SMC has no fan mode key (F0Md/F0md/FS!), so manual fan control is unavailable": "この Mac の SMC にはファンモードキー（F0Md/F0md/FS!）がないため、手動でファンを制御できません",
        "Timed out unlocking system mode for fan %d": "ファン %d のシステムモードの解除がタイムアウトしました",
        "Timer ended; macOS automatic control restored": "タイマーが終了し、macOS の自動制御に戻りました",
        "Unable to connect to AppleSMC (error %d).": "AppleSMC に接続できません（エラー %d）。",
        "Unable to connect to AppleSMC with privileges (%d)": "特権で AppleSMC に接続できません（%d）",
        "Unable to connect to the fan control service": "ファン制御サービスに接続できません",
        "Unable to enable %@ curve: %@": "%@のカーブを有効にできません：%@",
        "Unable to read fan %d": "ファン %d を読み取れません",
        "Unable to read the fan count": "ファンの数を読み取れません",
        "Unable to register control service: %@": "制御サービスを登録できません：%@",
        "Unable to run the system service command: %@": "システムサービスのコマンドを実行できません：%@",
        "Unable to update login item: %@": "ログイン項目を更新できません：%@",
        "Unable to write %@ (error %d).": "%@ に書き込めません（エラー %d）。",
        "Unknown cooling preset": "不明な冷却プリセットです",
        "Updates every 2 seconds": "2 秒ごとに更新",
        "Use custom actions to adjust temperature or fan speed": "カスタムアクションで温度または回転数を調整",
        "Used in Finder, Launchpad, and the menu bar panel.": "Finder、Launchpad、メニューバーパネルで使用されます。",
        "Waiting for approval · Open Settings": "承認待ち · 設定を開く",
        "Waiting for control service approval": "制御サービスの承認待ち",
        "Welcome to FanBar": "FanBar へようこそ",
        "Your curves are saved and apply once the service is available. %@.": "カーブは保存済みです。サービスが利用可能になると適用されます。%@。",
        "≈ %@ RPM": "≈ %@ RPM",
    ]
}
